[build]
  command = "cd fronend && npm install && npm run build"
  publish = "fronend/build"
  base = "."

[dev]
  command = "cd fronend && npm start"
  port = 3000
  publish = "fronend/build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
